language: python
python:
  - "3.6"
before_install:
  - export DJANGO_SETTINGS_MODULE=spc_portal.settings
install:
  - pip3 install -r requirements.txt
script:
  - cd src
  - flake8 .
  - python3 manage.py makemigrations
  - python3 manage.py migrate