name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Export environment variables
      run: |
        export DJANGO_SETTINGS_MODULE=spc_django.settings
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install coverage
    - name: Script
      run: |
        cp .env.example .env
        cd src
        flake8 .
        python3 manage.py makemigrations student
        python3 manage.py migrate student
        python3 manage.py makemigrations
        python3 manage.py migrate
        coverage run --source='.' manage.py test
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
   
